---
# Program/Department Title
title: Neuroscience
# Subdirectory (with / at only at beginning)
baseurl: /neuroscience

# Program Information
# Short tagline for tweets (<100 characters)
tagline: This is our life's work
# Longer descriptions for link previews (<250 characters)
description: 'Temple’s Neuroscience program teaches students to explore neural and brain function at multiple levels in a rapidly growing field. Our students study the neural basis of addiction, developmental disorders, ADHD, depression, anxiety and age-related disorders, among other fields.'
# List of related keywords for search engines
keywords: highered, college, university, philadelphia, Temple, neuroscience

# Address
address:
  building: Weiss Hall
  room:
  street: 1701 North 13th Street
  city: Philadelphia, PA 19122
  email: neuroscience@temple.edu
  phone: 215-204-3441

# Social Media
# Put in only the username unless otherwise noted
# If social media does not apply to your department, keep it blank or use the default values.
social:
  # Facebook - https://www.facebook.com/TempleNeuro
  # if your page does not have a custom URL, create one!
  facebook: TempleLiberalArts
  # Twitter - https://twitter.com/TempleUNeuro
  twitter: TULiberalArts
  # Instagram - https://www.instagram.com/tuliberalarts/
  instagram: TULiberalArts
  # Snapchat - USERNAME
  snapchat:
  # GitHub - https://github.com/USERNAME or https://github.com/USERNAME/REPO
  github:
  # DeviantArt - http://USERNAME.deviantart.com/
  deviantart:
  # Vimeo - https://vimeo.com/USERNAME
  vimeo:
  # YouTube - Paste the FULL URL below
  youtube:
  # LinkedIn - https://www.linkedin.com/groups?home=&gid=7480265
  linkedin:
  # Slack - Paste the FULL URL below
  slack:

# University & College Information
university:
  name: Temple University
  url: https://temple.edu/
college: 
  name: College of Liberal Arts
  url: https://liberalarts.temple.edu/

# Google Tag Manager OR Google Analytics
google_analytics: 


google_tag_manager: GTM-58ZL5B

# CSV/JSON/YAML data feeds URLs, to be fetched before each build
events-feed: https://liberalarts.temple.edu/events/neuroscience/csv
news-feed: https://liberalarts.temple.edu/news/neuroscience/csv
faculty-feed: https://liberalarts.temple.edu/profiles/neuroscience/csv

# Development Config
# If you do not have access to 'tutheme', use 'minima' instead.
theme: tutheme

# Global Site Config
# DO NOT edit below unless if you know what you're doing!
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    layout: page
permalink: /:title

# Prose
prose:
  rooturl: pages
  media: media
  ignore:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - index.html
  - _config.yml
  metadata:
    pages:
      - name: title
        field:
          element: text
          label: Title
      - name: permalink
        field:
          element: text
          label: Permalink
      - name: layout
        field:
          element: select
          label: Page layout
          options:
            - name: page
              value: page
            - name: faculty
              value: faculty
            - name: faculty2
              value: faculty2
            - name: home
              value: home

# Jekyll Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - s3_website.yml
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore
  - vendor
  - _site
  - node_modules
