---
title: Temple Neuroscience
baseurl: /neuroscience
production: https://www.temple.edu
url: https://www.temple.edu/neuroscience

tagline: This is our life's work
description: >-
  'The field of neuroscience is constantly expanding and exciting advancements
  are being made constantly. Temple University supports an interdisciplinary
  approach to this field of study.'
keywords: highered, university, philadelphia, Temple, neuroscience

address:
  building:
  room:
  street: 1801 North Broad Street
  city: Phialdelphia, PA 19122

university:
  name: Temple University
  url: https://temple.edu/

social:
  facebook: templeu
  twitter: TempleUniv
  instagram: TempleUniv

# Global Site Config
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: UTC
# collections:
#  pages:
#    title: Pages
#    output: true
#    layout: page
permalink: /:title

# Jekyll Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - s3_website.yml
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore
  - vendor
  - _site
  - node_modules
